# client-browser build stage
FROM node:9.11.1-alpine as build-stage
WORKDIR /app
COPY ./client-browser/package.json ./
RUN npm install
COPY client-browser/ .
RUN npm run build

# production stage
FROM meldon/willitrain
LABEL version=1.0.1
ENV VERSION 1.0.1
COPY --from=build-stage /app/dist /app/client-browser/dist
