@startuml



package "Clients " {
[Browser client]
[Mobile client]
}

package "3rd-party" {
[ECAD]
}

cloud AWS {

package "Web" {
[R API]
[Browser client] --> [R API]
[Mobile client] --> [R API]
}

package "Process" {
[Data Download] -> ECAD
[Data Process]
}

package "Data" {
NFS - [Data volume]: fetch  / process / store  data
[R API] .. NFS
[Data Process] <..> NFS
[Data Download] ..> NFS
}


}






@enduml
